services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.docker-01.rz-mgns.de"
      WEBSOCKET_ENABLED: "true"
      ROCKET_ADDRESS: "0.0.0.0"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 0.0.0.0:3008:80
